const fs=require('fs');
const [,, urlPart, out, log]=process.argv;
if(!urlPart||!out||!log){console.error('usage: node monitor_pro_page.js <urlPart> <out> <log>'); process.exit(2)}
const CDP='http://127.0.0.1:9226/json/list';
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
async function targets(){return await (await fetch(CDP)).json();}
async function evalWs(wsurl, expression){return new Promise((resolve,reject)=>{const ws=new WebSocket(wsurl);let done=false;const timer=setTimeout(()=>{if(!done){done=true;try{ws.close()}catch{};reject(new Error('timeout'))}},15000);ws.onopen=()=>ws.send(JSON.stringify({id:1,method:'Runtime.evaluate',params:{expression,returnByValue:true}}));ws.onmessage=ev=>{const msg=JSON.parse(ev.data);if(msg.id===1&&!done){done=true;clearTimeout(timer);try{ws.close()}catch{};resolve(msg.result?.result?.value ?? '')}};ws.onerror=e=>{if(!done){done=true;clearTimeout(timer);reject(e)}}})}
async function once(){const ts=await targets(); const t=ts.find(x=>(x.url||'').includes(urlPart)); if(!t) return {status:'NO_TARGET',text:'',len:0,buttons:[],url:''}; const expr=`(() => { const buttons=[...document.querySelectorAll('button')].map(b=>b.innerText||b.getAttribute('aria-label')).filter(Boolean); const nodes=[...document.querySelectorAll('[data-message-author-role="assistant"], section[data-testid^="conversation-turn"]')]; const turns=nodes.map((n,i)=>({i,len:(n.innerText||'').length,text:n.innerText||''})); const sorted=turns.sort((a,b)=>b.len-a.len); const text=sorted[0]?.text || document.body.innerText || ''; return JSON.stringify({url:location.href, title:document.title, buttons, len:text.length, text, tail:text.slice(-800), bodyTail:document.body.innerText.slice(-800)}); })()`; const raw=await evalWs(t.webSocketDebuggerUrl,expr); return JSON.parse(raw||'{}');}
(async()=>{let prev=-1, stable=0; fs.appendFileSync(log,new Date().toISOString()+' monitor start '+urlPart+'\n'); for(let i=0;i<180;i++){try{const o=await once(); const stop=o.buttons?.some(b=>/Stop answering|Thinking/i.test(b)); const len=o.len||0; if(len===prev) stable++; else {stable=0; prev=len;} const status=stop?'GENERATING':(len>1200&&stable>=2?'DONE':'WAITING'); const line=`${new Date().toISOString()} status=${status} len=${len} stable=${stable} url=${o.url} buttons=${JSON.stringify((o.buttons||[]).slice(-12))} tail=${String(o.tail||o.bodyTail||'').replace(/\s+/g,' ').slice(0,500)}\n`; fs.appendFileSync(log,line); console.log(line.trim()); if(status==='DONE'){fs.writeFileSync(out,o.text||''); console.log(`SAVED ${process.cwd()+'/'+out} chars=${(o.text||'').length} bytes=${Buffer.byteLength(o.text||'')}`); process.exit(0);} }catch(e){const line=new Date().toISOString()+' ERROR '+(e.message||e)+'\n'; fs.appendFileSync(log,line); console.error(line.trim());} await sleep(20000);} console.error('TIMEOUT'); process.exit(2);})();
